TRUNCATE SCHEMA CONTAINER AND COMMIT


INSERT INTO CONTAINER.WEB_GOAT_USER (PASSWORD, ROLE, USERNAME) VALUES ('testuser', 'WEBGOAT_USER', 'testuser');
INSERT INTO CONTAINER.WEB_GOAT_USER (PASSWORD, ROLE, USERNAME) VALUES ('testuser', 'WEBGOAT_USER', 'testuser2');

INSERT INTO CONTAINER.USER_PROGRESS (ID, USERNAME) VALUES (1, 'testuser');
INSERT INTO CONTAINER.USER_PROGRESS (ID, USERNAME) VALUES (2, 'testuser2');
